-- file=随机名字库.xlsx[前缀] key=value
module('TableNameFirst', package.seeall)
TableNameFirst["不朽的"]={["value"]="不朽的"}
TableNameFirst["优雅的"]={["value"]="优雅的"}
TableNameFirst["低调的"]={["value"]="低调的"}
TableNameFirst["冰冻的"]={["value"]="冰冻的"}
TableNameFirst["可爱的"]={["value"]="可爱的"}
TableNameFirst["哀伤的"]={["value"]="哀伤的"}
TableNameFirst["天才的"]={["value"]="天才的"}
TableNameFirst["奇葩的"]={["value"]="奇葩的"}
TableNameFirst["奔放的"]={["value"]="奔放的"}
TableNameFirst["奢华的"]={["value"]="奢华的"}
TableNameFirst["娇小的"]={["value"]="娇小的"}
TableNameFirst["娇羞的"]={["value"]="娇羞的"}
TableNameFirst["娴熟的"]={["value"]="娴熟的"}
TableNameFirst["寂寞的"]={["value"]="寂寞的"}
TableNameFirst["幻想的"]={["value"]="幻想的"}
TableNameFirst["忧伤的"]={["value"]="忧伤的"}
TableNameFirst["拉风的"]={["value"]="拉风的"}
TableNameFirst["无敌的"]={["value"]="无敌的"}
TableNameFirst["时尚的"]={["value"]="时尚的"}
TableNameFirst["最后的"]={["value"]="最后的"}
TableNameFirst["机智的"]={["value"]="机智的"}
TableNameFirst["洋气的"]={["value"]="洋气的"}
TableNameFirst["温柔的"]={["value"]="温柔的"}
TableNameFirst["灵活的"]={["value"]="灵活的"}
TableNameFirst["猥琐的"]={["value"]="猥琐的"}
TableNameFirst["碉堡的"]={["value"]="碉堡的"}
TableNameFirst["神秘的"]={["value"]="神秘的"}
TableNameFirst["绝望的"]={["value"]="绝望的"}
TableNameFirst["耀眼的"]={["value"]="耀眼的"}
TableNameFirst["自由的"]={["value"]="自由的"}
TableNameFirst["萌萌的"]={["value"]="萌萌的"}
TableNameFirst["迅捷的"]={["value"]="迅捷的"}
TableNameFirst["邋遢的"]={["value"]="邋遢的"}
TableNameFirst["邪恶的"]={["value"]="邪恶的"}
TableNameFirst["闷骚的"]={["value"]="闷骚的"}
